# Informations de connexion a la base de donnees
database:
  host: 'localhost'
  database: 'minecraft'
  user: 'user'
  password: 'password'
  port: 3306

# Information sur le serveur
server:
  name: 'ENSILAN'
  ip: 'ensilan.fr'
